[package]
name = "fusee"
version = "0.1.0"
authors = ["Austin Hartzheim <inbox@austinhartzheim.me>"]
edition = "2018"
license = "GPL-2.0-only"

[dependencies]
libc = "0.2.138"
clap = "2.34.0"
rusb = "0.7.0"
